### ISSUE TITLE
Missing liblwjgl on ARM Devices

### ISSUE THREAD

**Issue by hny3494317690** [Andy-K-Sparklight/Alicorn#135]
这款启动器是我找到的唯一一款可以兼容arm64的mc启动器，我将他安装在我的arm64 ubuntu下，并按照网络教程安装了完整的Java18和相应库，但是启动时他提醒我Failed to locate library:liblwjgl.so，我上百度和谷歌都有查过，许多人都遇到这个问题，但是他们的解决方法不适用于我，所以我想求助开发者针对这一问题设计或提出一个可行方案...

(Translated by collaborators)

This launcher is the only mc launcher I found that is compatible with arm64. I installed it under my arm64 ubuntu and installed the complete Java18 and corresponding libraries according to the online tutorial, but he reminded me when I started it. Failed to locate library:liblwjgl.so, I have checked on Baidu and Google, many people have encountered this problem, but their solutions do not apply to me, so I want to help developers design or propose this problem A possible solution...

**Comment by Andy-K-Sparklight** [comment]
ARM support is still in the experimental stage, the compilation of many libraries is very immature, and there are great difficulties in implementation. We're working on a new launcher on top of Alicorn, and may bring this feature back into the plans, and maybe choose to support our work (whatever that is) if it's very much desired?
Another note: ARM devices are not officially supported by Mojang.

**Comment by Andy-K-Sparklight** [comment]
I'll keep this issue open. If anyone has good ideas, please comment.

**Comment by Andy-K-Sparklight** [comment]
Also it might be caused by the lack of support of 1.19, which is a general problem (bug).
The launch problem of 1.19 has been fixed in Core 49.
If it still cannot run (probably), feel free to comment.

**Comment by Andy-K-Sparklight** [comment]
See also #130

**Comment by skjsjhb** [comment]
您好。
抱歉没有及时回复。
Alicorn 的原始开发者已经离开社区，Alicorn 现在由我负责必要的维护工作。
有关您的 Issue，Mojang 现已提供 arm 的官方支持，Alicorn 所提供的兼容库已经过时，不再需要。
这个 Issue 将被关闭，如果有追加问题，您可以再创建一个 Issue。
