### ISSUE TITLE
一个关于翻译的惊天大难题！

### ISSUE THREAD

**Issue by iamyou** [Andy-K-Sparklight/Alicorn#32]
Alicorn正在更新联机系统！但是在这个要说名道姓并且国际化的时代，一个东西必须要有一个好听的名字才能吸引大家！
正如小马利亚有Cutie Map指引你带给别人FriendShip一样，Alicorn推出了Cutie Connect让你在Minecraft世界中带给别人Friendship
但是呢，它的中文直译略显尴尬，什么，你不信？我给你念一下：
**可爱连接**
是不是稍微。。有一点不对劲？如果有更好的名字，不如提出来，不然的话，可爱连接就真的要叫可爱连接了（

**Comment by Andy-K-Sparklight** [comment]
"友谊接力" seems great!
I'll just take it :)

**Comment by DearJasker** [comment]
You should thank meO(∩_∩)O
