### ISSUE TITLE
Some tips do not appear in BuildUp

### ISSUE THREAD

**Issue by iamyou** [Andy-K-Sparklight/Alicorn#71]
- Core-version: `36` 

## Describe
https://github.com/Andy-K-Sparklight/Alicorn/blob/78b812d4df7d4d4746dd6de0dada9f41c95eec72/resources/shared/defaults/PonyCN.lang#L2838-L2869
## Problem recurrence
Try to build up a mod pack

**Comment by Andy-K-Sparklight** [comment]
Just because the entire key could not be found doesn't mean it's not referenced.
Read the code carefully, some keys are referenced with prefix, for example:
```ts
const fun = (s) => {
    return tr("A.B.C." + s);
}
fun("D"); // Already referenced A.B.C.D
```
