### ISSUE TITLE
Can not download JRE 17 via Alicorn

### ISSUE THREAD

**Issue by iamyou** [Andy-K-Sparklight/Alicorn#74]
- Core-version: `36` 

## Describe
There is no JRE at https://mirror.tuna.tsinghua.edu.cn/AdoptOpenJDK/17/**JRE**/x64/ so Alicorn can not download JAVA17
## Problem recurrence
Download JAVA 17 via Alicorn

**Comment by Andy-K-Sparklight** [comment]
We'll use jdk instead.

**Comment by Andy-K-Sparklight** [comment]
Fixed in commit 862d0afd75362d7206bdd3fc1260e12ceb562209
