### ISSUE TITLE
Choose ModLoader Version

### ISSUE THREAD

**Issue by Andy-K-Sparklight** [Andy-K-Sparklight/Alicorn#92]
As user suggested.

**Comment by Andy-K-Sparklight** [comment]
We've found it really hard when it comes to Forge -- there isn't a full mj2fg versions map. We also cannot send requests to SaaS APIs.

As for Fabric, mostly versions does not matter.

So this issue can be temporarily archived. Open it if necessary one day.

**Comment by skjsjhb** [comment]
This feature has landed in recent releases. Forge is also supported.
