### ISSUE TITLE
Launcher Language

### ISSUE THREAD

**Issue by DoisPontinhos** [Andy-K-Sparklight/Alicorn#97]
Hello, is it possible to change the launcher language ?

**Comment by Andy-K-Sparklight** [comment]
Currently only Simplified Chinese are supported. However, if necessary, translations will be very easy :)

Need English (or Modern Equish) version? I can add it to our goals.

**Comment by Andy-K-Sparklight** [comment]
OK, most keys have been translated.
There are still some components in Alicorn which were hardcoded. To make them support i18n will take a while.

Keep this issue open and I'll keep pushing commits about this :)

**Comment by DoisPontinhos** [comment]
Thanks for the help :)

**Comment by Andy-K-Sparklight** [comment]
Closed as resolved, since translations seem fine.
